name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Test input"
        required: false
        default: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test dispatch works!"
